[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.18"
remappings = ["chainlink/=lib/chainlink/contracts/src", "forge-std=lib/forge-std/src/", "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config