export MAINNET_RPC_URL=<MAIINET_RPC_URL_WITH_API_KEY>
export ETHERSCAN_API_KEY=<ETHERSCAN_API_KEY>
export PRIVATE_KEY=<PRIVATE_KEY>
export DEPLOYMENT_NETWORK=<DEPLOYMENT_NETWORK_EXAMPLE_GOERLI_MAINNET_ETC>
export CURVE_POOL_MAINNET=<CURVE_POOL_ADDRESS>
export YEARN_VAULT_MAINNET=<YEARN_VAULT_ADDRESS>
export POOL_TOKEN_1_MAINNET=<USDT_ADDRESS>
export POOL_TOKEN_2_MAINNET=<WBTC_ADDRESS>
export POOL_TOKEN_3_MAINNET=<WETH_ADDRESS>
forge script script/YearnPositionTWAPOracle.s.sol --rpc-url $MAIINET_RPC_URL  --broadcast --private-key $PRIVATE_KEY  --verify -vvvv --etherscan-api-key $ETHERSCAN_API_KEY